name: cabeson
favicon: null
layout_spectrum: 0.25497995782643557
typography_spectrum: 0.26760671311058104
title: Kitty Cat Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8050001836381853
  lightness: 0.7057728795334697
  saturation: 0.6641056523658335
  rhythmicContrast: 0.16850079782307148
purpose: []
